"""Add jira ticket

Revision ID: 649d1362714e
Revises: 3a962200398c
Create Date: 2026-07-11 04:23:16.526995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649d1362714e'
down_revision: Union[str, Sequence[str], None] = '3a962200398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('jira_ticket', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('assigned_team', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('incident_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'incident_status')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'assigned_team')
    op.drop_column('alerts', 'jira_ticket')
    # ### end Alembic commands ###
